
create database LAB1;
show databases;
use LAB1;
create table CLIENT_MASTER(CLIENTNO varchar(6), CLIENT_NAME varchar(20), ADDRESS_1 varchar(30), ADDRESS_2 VARCHAR(30), CITY varchar(15), 
PINCODE INT, STATE VARCHAR(15),
BALDUE DECIMAL(10,2));
create table PRODUCT_MASTER(PRODUCTNO VARCHAR(6), DESCRIPTION VARCHAR (15), PROFITPERCENT DECIMAL(4,2), UNIT_MEASURE VARCHAR(10), 
QTYONHAND INT, REORDER_VL INT, 
SELLPRICE DECIMAL(8,2), COSTPRICE DECIMAL(8,2));
create table SALESMAN_MASTER(SALESMANNO VARCHAR(6), SALESMANNAME VARCHAR(20), ADDRESS_1 VARCHAR (30), ADDRESS_2 VARCHAR(30), 
CITY VARCHAR(20), PINCODE INT,
 STATE VARCHAR (20), SALAMT double precision,
TGTTOGET DECIMAL(20,3), YTDSALES DOUBLE(6,2), REMARKS VARCHAR(60));

INSERT INTO CLIENT_MASTER(CLIENTNO, CLIENT_NAME, CITY, PINCODE, STATE, BALDUE) VALUES ('C0006', 'DEEPAK SHARMA', 'MANGALORE', 560050, 'KARNATAKA', 0);
SELECT * FROM CLIENT_MASTER;

INSERT INTO PRODUCT_MASTER(PRODUCTNO ,DESCRIPTION,PROFITPERCENT,UNIT_MEASURE,QTYONHAND,REORDER_VL,SELLPRICE,COSTPRICE)VALUES 
('P08865', 'SKIRTS', 5, 'PIECE', 75, 30,450, 300);
SELECT * FROM PRODUCT_MASTER;



INSERT INTO SALESMAN_MASTER(SALESMANNO, SALESMANNAME, ADDRESS_1, ADDRESS_2, CITY, PINCODE,STATE) VALUES
('S00001','AMAN','A/14', 'WORLI', 'MUMBAI', 40002, 'MAHARASHTRA');
SELECT * FROM SALESMAN_MASTER;









